[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "credit-risk-scoring"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = ["kedro~=1.3.1"]

[project.scripts]
credit-risk-scoring = "credit_risk.__main__:main"

[project.entry-points."kedro.hooks"]

[tool.setuptools.dynamic.version]
attr = "credit_risk.__version__"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.kedro]
package_name = "credit_risk"
project_name = "Credit Risk Scoring"
kedro_init_version = "1.3.1"
tools = "['None']"
example_pipeline = "False"
source_dir = "src"

[tool.kedro_telemetry]
project_id = "a87e4dd810d04957a996f58907683584"
